### ISSUE TITLE
Add v0.1 tag for inclusion in MELPA Stable

### ISSUE THREAD

**Issue by jrblevin** [mswift42/silkworm-theme#2]
I like the theme; thanks for sharing it. However, I use MELPA Stable and it's not included there because there is no "stable release". I think all you need to do is push a `v0.1` tag to GitHub and it will show up there also.

**Comment by mswift42** [comment]
Thanks, I'll look into it.

**Comment by mswift42** [comment]
Just added 0.1 release :)

**Comment by jrblevin** [comment]
It worked—thanks a lot!

<https://stable.melpa.org/#/silkworm-theme>

**Comment by mswift42** [comment]
Awesome.
