### ISSUE TITLE
Selection from ivy-list is not clearly seen

### ISSUE THREAD

**Issue by tmythicator** [mswift42/silkworm-theme#4]
I am not sure, whether it is ivy issue or not, but with this theme I can not really see the current item from ivy list:
![image](https://user-images.githubusercontent.com/9789061/66256552-39593d00-e78f-11e9-86d9-36f87f2e662e.png)

My suggestion would be to add a line in the same kind of fashion:
``` emacs-lisp
   ;; Ivy
   `(ivy-current-match ((,class (:foreground ,fg3 :inherit highlight :underline t))))
```

**Comment by mswift42** [comment]
Fixed with commit [8e940ba23039b56018a35e0d11822554965b21e2](https://github.com/mswift42/silkworm-theme/commit/8e940ba23039b56018a35e0d11822554965b21e2).
